# Generated by Django 4.0.5 on 2023-01-02 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_joblisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='salary_max',
            field=models.IntegerField(blank=True, default=5000, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='salary_min',
            field=models.IntegerField(blank=True, default=4000, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='user',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='job_description',
            field=models.TextField(blank=True),
        ),
    ]
