# Generated by Django 4.0.5 on 2023-01-02 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_joblisting_salary_max_joblisting_salary_min_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobListing',
        ),
    ]
